name: Build Windows Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5 requests pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name BBDown_GUI `
          --icon bbdown_icon.ico `
          --add-data "bbdown_icon.ico;." `
          bbdown_gui.py
          
    - name: Package artifact
      run: |
        Compress-Archive -Path dist\BBDown_GUI.exe -DestinationPath BBDown_GUI_Windows.zip
        mkdir artifact
        Move-Item BBDown_GUI_Windows.zip artifact/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BBDown_GUI_Windows
        path: artifact/BBDown_GUI_Windows.zip
